/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex('cafes').insert([
    {
      id: 1,
      name: 'Maranui Cafe',
      longitude: 174.7762,
      latitude: -41.2933,
      image: 'maranui_cafe.jpg',
      google_id: 'example_google_id_1',
      directions_url: 'https://goo.gl/maps/example1',
      street_address: '1 Lyall Bay Rd',
      suburb: 'Lyall Bay',
      city: 'Wellington',
    },
    {
      id: 2,
      name: 'Cafe L’affare',
      longitude: 174.7798,
      latitude: -41.2912,
      image: 'cafe_laffare.jpg',
      google_id: 'example_google_id_2',
      directions_url: 'https://goo.gl/maps/example2',
      street_address: '27 College Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
    {
      id: 3,
      name: 'Midnight Espresso',
      longitude: 174.773,
      latitude: -41.2906,
      image: 'midnight_espresso.jpg',
      google_id: 'example_google_id_3',
      directions_url: 'https://goo.gl/maps/example3',
      street_address: '178 Cuba Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
    {
      id: 4,
      name: 'The Flight Coffee Hangar',
      longitude: 174.7778,
      latitude: -41.284,
      image: 'flight_coffee_hangar.jpg',
      google_id: 'example_google_id_4',
      directions_url: 'https://goo.gl/maps/example4',
      street_address: '15 Wigan Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
    {
      id: 5,
      name: 'Mischief & Mayhem',
      longitude: 174.781,
      latitude: -41.292,
      image: 'mischief_mayhem.jpg',
      google_id: 'example_google_id_5',
      directions_url: 'https://goo.gl/maps/example5',
      street_address: '124 Victoria Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
    {
      id: 6,
      name: 'Leeds Street Bakery',
      longitude: 174.775,
      latitude: -41.2915,
      image: 'leeds_street_bakery.jpg',
      google_id: 'example_google_id_6',
      directions_url: 'https://goo.gl/maps/example6',
      street_address: '7 Leeds Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
    {
      id: 7,
      name: 'The Hanging Ditch',
      longitude: 174.7775,
      latitude: -41.295,
      image: 'hanging_ditch.jpg',
      google_id: 'example_google_id_7',
      directions_url: 'https://goo.gl/maps/example7',
      street_address: '16 Victoria Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
    {
      id: 8,
      name: 'Café Polo',
      longitude: 174.7815,
      latitude: -41.2935,
      image: 'cafe_polo.jpg',
      google_id: 'example_google_id_8',
      directions_url: 'https://goo.gl/maps/example8',
      street_address: '21 Dixon Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
    {
      id: 9,
      name: 'Café Bretto',
      longitude: 174.782,
      latitude: -41.29,
      image: 'cafe_bretto.jpg',
      google_id: 'example_google_id_9',
      directions_url: 'https://goo.gl/maps/example9',
      street_address: '5 Tory Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
    {
      id: 10,
      name: 'Mokushido Café',
      longitude: 174.778,
      latitude: -41.296,
      image: 'mokushido_cafe.jpg',
      google_id: 'example_google_id_10',
      directions_url: 'https://goo.gl/maps/example10',
      street_address: '2/4 Wallace Street',
      suburb: 'Te Aro',
      city: 'Wellington',
    },
  ])
}
